FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY exam_intent_model ./exam_intent_model
COPY nlp.py ask_ai.py ./

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "nlp:app", "--host", "0.0.0.0", "--port", "8000"]